package fr.cy.model.graph.element;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.io.Serializable;
import java.io.*;

import fr.cy.model.agent.Agent;
import fr.cy.model.agent.AgentSettings;
import fr.cy.model.agent.behaviour.properties.AgentDecisionalProperties;
import fr.cy.model.fire.Fire;
import fr.cy.model.simulation.SimulationSettings;
import fr.cy.model.stress.StressInducing;

/**
 * Abstract class representing a graph element.
 * * This class serves as the base for all graph elements such as nodes and
 * edges.
 * It manages shared properties including a unique identifier, fire state,
 * congestion tracking, and stress metrics.
 * * @author GI3A
 * 
 * @version 1.0
 */
public abstract class GraphElement implements StressInducing, Serializable {
    private static final long serialVersionUID = 1L;

    private final int id;
    private List<Agent> agents;
    private double capacity;
    private boolean isForcedCongested = false;
    private int forcedCongestionTicks = 0;
    private Fire initialFire;

    /** Cached total stress including neighbors. */
    private double cachedTotalStressInducedIncludingNeighbors = 0;
    /** Cached stress induced by this element alone. */
    private double cachedTotalStressInducedByThisElement = 0;

    private Fire fire;

    // Statistics
    private int totalAgentsCount = 0;
    private int timesFull = 0;
    private double maxCongestion = 0;
    private double sumCongestion = 0;
    private int congestionMeasureCount = 0;

    /**
     * Constructs a graph element with a unique ID and capacity.
     * * @param id Unique identifier.
     * 
     * @param capacity Maximum capacity in m².
     */
    protected GraphElement(int id, double capacity) {
        this.id = id;
        this.agents = new ArrayList<>();
        this.capacity = Math.max(0.1, capacity);
        removeFire();
    }

    /**
     * Retrieves the list of neighboring elements.
     * * @return List of neighboring {@link GraphElement}s.
     */
    public abstract List<GraphElement> getNeighbors();

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        GraphElement element = (GraphElement) o;
        return getId() == element.getId();
    }

    /** @return The unique identifier of this element. */
    public int getId() {
        return id;
    }

    /** @return True if the element is on fire. */
    public boolean isOnFire() {
        return fire != null;
    }

    public Fire getFire() {
        return fire;
    }

    public void setFire(Fire fire) {
        this.fire = fire;
    }

    public void removeFire() {
        this.fire = null;
    }

    /** @return The list of agents currently located on this element. */
    public List<Agent> getAgents() {
        return agents;
    }

    /**
     * Adds an agent if capacity permits.
     * @param a The agent to add.
     * 
     * @return True if successful, false if the element is at full capacity.
     */
    public boolean addAgent(Agent a) {
        if (!isFull()) {
            agents.add(a);
            incrementTotalAgentsCount();
            recordCongestionMeasure();
            if (isFull())
                incrementTimesFull();
            return true;
        }
        return false;
    }

    /** @return True if current congestion exceeds 70%. */
    public boolean isCongested() {
        return getCongestion() > 0.7;
    }

    //FIXME : proper integration of this method for forced congestion + code duplication with addAgent 
    public boolean forceAddAgent(Agent a) { //TODO
        if (isFull())
            setForcedCongestion(true);
        agents.add(a);  
        incrementTotalAgentsCount();
        recordCongestionMeasure();  
        if (isFull())
            incrementTimesFull();
        return true;
    }


    /**
     * Calculates an attractiveness multiplier for an agent based on local
     * conditions.
     * * @param agentState Agent decision properties.
     * 
     * @return Score multiplier (values < 1 decrease attractiveness).
     */
    public double getScoreMultiplierForAgent(AgentDecisionalProperties agentState) {
        double scoreMult = 1.0;
        if (isOnFire()) {
            Fire f = getFire();
            scoreMult *= 0.1 / (1.0 + f.getIntensity() + f.getSmokeLevel() + f.getSpreadRate());
        }
        double congestion = getCongestion();
        if (isCongested()) {
            scoreMult *= 0.4 * (1.0 + congestion - agentState.getCongestionTolerance());
        }
        double stress = getStressInducingImpact();
        if (stress > 0.90) {
            scoreMult *= 0.4 * (1.0 + stress - agentState.getStressTolerance());
        }
        return scoreMult;
    }

    /**
     * Computes and caches stress generated by this element alone.
     * * @param tickDuration The duration of the simulation step in seconds.
     * 
     * @return Cached stress value.
     */
    public double updateStressGeneratedByThisElement(double tickDuration) {
        double stress = 0;
        double congestion = getCongestion();
        stress += congestion * congestion * 0.4;
        double meanStressFromAgents = getAgentsTotalStress() / Math.max(1, getAgents().size());
        stress += meanStressFromAgents * meanStressFromAgents * 0.4;
        if (isOnFire())
            stress += 0.2 * getFire().getIntensity();

        cachedTotalStressInducedByThisElement = Math.min(stress, 1.0) * tickDuration / 0.016;
        return cachedTotalStressInducedByThisElement;
    }

    public double getCachedTotalStressInducedByThisElement() {
        return cachedTotalStressInducedByThisElement;
    }

    /**
     * Computes and caches stress including neighborhood impact.
     * 
     * @return The total stress value.
     */
    public double updateCachedTotalStressInducedIncludingNeighbors() {
        double neighbouringStress = 0;
        for (GraphElement neighbor : getNeighbors()) {
            neighbouringStress += neighbor.getCachedTotalStressInducedByThisElement();
        }
        double thisElementStress = getCachedTotalStressInducedByThisElement();
        double totalStress = Math.min(thisElementStress + neighbouringStress * neighbouringStress * 0.4, 1.0);
        cachedTotalStressInducedIncludingNeighbors = totalStress;
        return totalStress;
    }

    /** @return Sum of stress levels for all agents on this element. */
    public double getAgentsTotalStress() {
        double totalStress = 0;
        for (Agent agent : agents)
            totalStress += agent.getStressLevel();
        return totalStress;
    }

    @Override
    public double getStressInducingImpact() {
        return getCachedTotalStressInducedIncludingNeighbors();
    }

    /** @param a Agent to remove. */
    public void removeAgent(Agent a) {
        if (agents.remove(a))
            recordCongestionMeasure();
    }

    public double getCapacity() {
        return capacity;
    }

    public void setCapacity(double capacity) {
        this.capacity = Math.max(0.1, capacity);
    }

    /** @return Sum of surface areas occupied by agents. */
    public double getOccupiedSpace() {
        double occupied = 0;
        for (Agent agent : agents)
            occupied += agent.getSurfaceAreaTakenByAgent();
        return occupied;
    }

    /** @return Congestion level (0.0 to 1.0). */
    public double getCongestion() {
        return Math.min(getOccupiedSpace() / getCapacity(), 1);
    }

    /** @return True if element capacity is reached. */
    public boolean isFull() {
        return getOccupiedSpace() >= capacity;
    }

    public double getCachedTotalStressInducedIncludingNeighbors() {
        return cachedTotalStressInducedIncludingNeighbors;
    }

    // Statistics methods
    public void incrementTotalAgentsCount() {
        this.totalAgentsCount++;
    }

    public int getTotalAgentsCount() {
        return totalAgentsCount;
    }

    public void incrementTimesFull() {
        this.timesFull++;
    }

    public int getTimesFull() {
        return timesFull;
    }

    public void recordCongestionMeasure() {
        double currentCongestion = getCongestion();
        sumCongestion += currentCongestion;
        congestionMeasureCount++;
        if (currentCongestion > maxCongestion)
            maxCongestion = currentCongestion;
    }

    public double getMaxCongestion() {
        return maxCongestion;
    }

    public double getAverageCongestion() {
        return (congestionMeasureCount == 0) ? 0 : sumCongestion / congestionMeasureCount;
    }

    public int getCongestionMeasureCount() {
        return congestionMeasureCount;
    }

    public double getDamageForAgent(Agent agent) {
        return getDamageForAgent(agent, SimulationSettings.getInstance().getTickDuration());
    }

    public double getDamageForAgent(Agent agent, double duration) {
        double damage = (getCongestion() > 1 ? 1 : 0) * duration;
        if (isOnFire())
            return damage + getFire().getDamageForAgent(duration);
        return damage;
    }

    public double getMaxAgentSpeed() {
        double effectiveCongestion = Math.min(getCongestion(), 0.9);
        double congestionFactor = 1.0 - effectiveCongestion;
        double calculatedSpeed = AgentSettings.getInstance().getMAX_RUNNING_SPEED() * congestionFactor;
        return isOnFire() ? calculatedSpeed * 1.5 : Math.max(calculatedSpeed, 0.1);
    }

    public void setInitialState() {
        this.initialFire = (getFire() != null) ? getFire() : null;
    }

    public void reset() {
        agents.clear();
        setFire((initialFire != null) ? initialFire : null);
        maxCongestion = 0;
        sumCongestion = 0;
        congestionMeasureCount = 0;
        timesFull = 0;
        totalAgentsCount = 0;
        cachedTotalStressInducedByThisElement = 0;
        cachedTotalStressInducedIncludingNeighbors = 0;
    }

    public void setForcedCongestion(boolean congested) {
        this.isForcedCongested = congested;
        if (congested)
            this.forcedCongestionTicks = 0;
    }

    public boolean isForcedCongested() {
        return isForcedCongested;
    }

    public void updateForcedCongestion() {
        if (isForcedCongested) {
            forcedCongestionTicks++;
            if (forcedCongestionTicks >= 2) {
                isForcedCongested = false;
                forcedCongestionTicks = 0;
            }
        }
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        in.defaultReadObject();
        if (agents == null)
            agents = new ArrayList<>();
    }
}